name = "QuillenSuslin"
version = "0.1.0"
keywords = ["math"]
defaultTargets = ["QuillenSuslin"]

[leanOptions]
pp.unicode.fun = true                  # pretty-prints `fun a ↦ b`
autoImplicit = false
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = false
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
git = "https://github.com/Thmoas-Guan/mathlib4_fork.git"
rev = "Localization-of-Regular-(Local)-Ring"


[[lean_lib]]
name = "QuillenSuslin"
